name: anderfit
description: Aplicativo de treino, evolução e acompanhamento ANDERFIT.
publish_to: none
version: 0.7.0+8
environment:
  sdk: ^3.10.0
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  pdfx:
    path: third_party/pdfx
  supabase_flutter: ^2.17.2
  http: ^1.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/pdfs/adaptação/
    - assets/pdfs/avançado feminino/
    - assets/pdfs/avançado masculino/
    - assets/pdfs/feminino em casa/
    - assets/pdfs/iniciante feminino/
    - assets/pdfs/iniciante masculino/
    - assets/pdfs/intermediario feminino/
    - assets/pdfs/intermediario masculino/
    - assets/pdfs/masculino em casa/
    - assets/pdfs/receitas/
  fonts:
    - family: Anderfit
      fonts:
        - asset: assets/fonts/roboto-regular.ttf
        - asset: assets/fonts/roboto-bold.ttf
          weight: 700
        - asset: assets/fonts/roboto-black.ttf
          weight: 900
